feat: Add condition to send error message - run step

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -21,7 +21,7 @@ jobs:
         run: mkdir -p cypress/results
 
       - name: Run Cypress tests
-        run: npx cypress run --reporter json --reporter-options output=cypress/results/results.json
+        run: npx cypress run --reporter json --reporter-options output=cypress/results/results.json || echo "Cypress tests failed
 
       - name: Send results to Slack
         run: |
